# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rocket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='', max_length=30)),
                ('account_name', models.CharField(default='', max_length=60)),
                ('bank_name', models.CharField(default='', max_length=30)),
                ('payment_means', models.CharField(choices=[('B', 'Bank Deposit'), ('A', 'ATM Transfer'), ('M', 'Mobile Transfer')], default='B', max_length=5)),
                ('payment_snapshot', models.ImageField(blank=True, height_field='img_height', null=True, upload_to=rocket.models.upload_location, width_field='img_width')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('phone_number', models.CharField(blank=True, default='', max_length=11)),
                ('email', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rocket.Subscriber'),
        ),
    ]
